config/routes.rb
Rails.application.routes.draw do
  # get 'new_action', to: 'foreman_probing/hosts#new_action'
  namespace :foreman_probing do
    resources :scans, :only => [:create, :new, :show, :index] do
      member do
        get :rerun
      end
    end

    constraints(:id => /[^\/]+/) do
      resources :hosts do
        member do
          get 'open_ports'
        end
      end
    end

    namespace :api do
      scope "(:apiv)", :module => :v2, :defaults => {:apiv => 'v2'}, :apiv => /v2/, :constraints => ApiConstraints.new(:version => 2, :default => true) do
        resources :scans, :only => [:create, :index, :show] do
          member do
            get :rerun
          end
        end
      end
    end
  end
end

app/models/concerns/foreman_probing/foreman_tasks_task_extensions.rb
module ForemanProbing
  module ForemanTasksTaskExtensions
    def self.prepended(base)
      base.instance_eval do
        has_one :scan, :dependent => :nullify, :foreign_key => 'task_id', :class_name => '::ForemanProbing::ScanHost'
      end
    end
  end
end

app/models/concerns/foreman_probing/host_extensions.rb
module ForemanProbing
  module HostExtensions
    def self.prepended(base)
      base.instance_eval do
        has_many :scan_hosts, :class_name => '::ForemanProbing::ScanHost', :foreign_key => :host_id
        has_many :scans, :through => :scan_hosts, :class_name => '::ForemanProbing::Scan'
      end
    end
  end
end

app/models/concerns/foreman_probing/subnet_extensions.rb
module ForemanProbing
  module SubnetExtensions
    extend ActiveSupport::Concern

    included do
      # execute callbacks
      has_many :probing_proxies, :dependent => :destroy
    end

    # create or overwrite instance methods...
    def probe!(probe)

    end

    module ClassMethods
      # create or overwrite class methods...
      def class_method_name
      end
    end
  end
end

app/models/foreman_probing/fact_name.rb
module ForemanProbing
  class FactName < ::FactName
    # Define the class that fact names that come from Ansible should have
    # It allows us to filter facts by origin, and also to display the origin
    # in the fact values table (/fact_values)
    def origin
      'foreman_probing/Network Scan'
    end
    
  end
end

app/models/foreman_probing/port.rb
module ForemanProbing
  class Port < ActiveRecord::Base
    belongs_to :probing_facet, :class_name => '::ForemanProbing::ProbingFacet'
    has_many :services

    def update_from_facts(protocol, number, facts)
      self.protocol = protocol
      self.number = number
      self.state = facts[:state]
    end

    def update_from_port(port)
      protocol = port.protocol
      number = port.number
      state = port.state
      port.services.reject { |service| self.services.map(&:name).include? service.name }.each do |service|
        self.services << service
      end
    end
  end
end

app/models/foreman_probing/probing_facet.rb
module ForemanProbing
  class ProbingFacet < ActiveRecord::Base
    include Facets::Base
    
    def self.table_name
      'foreman_probing_probing_facets'
    end

    validates :host, :presence => true, :allow_blank => false

    has_many :scanned_ports, :class_name => 'Port'
    has_many :services, :through => :scanned_ports

    def online?

    end

    def refresh

    end

    def ping!

    end

  end
end

app/models/foreman_probing/scan.rb
module ForemanProbing
  class Scan < ActiveRecord::Base
    include Taxonomix

    default_scope -> do
      with_taxonomy_scope do
        order(:id => 'desc')
      end
    end

    belongs_to :task, :class_name => '::ForemanTasks::Task'
    has_one :targeting
    has_one :scan_host
    has_many :hosts, :through => :scan_host, :class_name => 'Host::Managed'
    belongs_to :smart_proxy

    attr_accessor :direct, :target_kind, :search_query, :subnet_id

    def ports
      if @ports.nil?
        return [] if raw_ports.nil?
        ranges = raw_ports.split(',')
        ports = ranges.map do |range|
          range.split('-').map do |from, to|
            to.nil? ? from : (from..to).entries
          end
        end
        @ports = ports.flatten.map(&:chomp).map(&:to_i)
      end
      @ports
    end

    def available_scan_types
      ['TCP', 'UDP', 'ICMP']
    end

    def target_kinds
      ['Direct', 'Subnet', 'Host', 'Proxy']
    end

  end
end

app/models/foreman_probing/scan_composer.rb
module ForemanProbing
  class ScanComposer

    attr_accessor :targeting, :ports, :probe, :proxy

    TARGETING_TYPES = %w(direct subnet host proxy).freeze

    def self.new_from_params(params)
      self.new.tap do |c|
        c.targeting = c.targeting_from_params(params)
        c.ports = c.ports_from_params(params)
        c.probe = params[:scan_type]
        c.proxy = c.proxy_from_params(params)
      end
    end

    def self.new_from_scan(scan)
      self.new.tap do |c|
        c.targeting = scan.targeting.dup
        c.ports = scan.raw_ports
        c.probe = scan.scan_type
        c.proxy = scan.smart_proxy
      end
    end

    def compose!
      if @scan.nil?
        @scan = ForemanProbing::Scan.new
        @scan.targeting = targeting
        @scan.target_kind = targeting.target_kind
        @scan.smart_proxy = proxy
        @scan.scan_type = probe
        @scan.raw_ports = ports

        case targeting
        when ::ForemanProbing::Targeting::Direct
          @scan.direct = targeting.raw_targets
        when ::ForemanProbing::Targeting::Subnet
          @scan.subnet_id = targeting.raw_targets.to_i
        when ::ForemanProbing::Targeting::Search
          @scan.search_query = targeting.raw_targets
        end
      end
      @scan
    end

    def proxy_from_params(params)
      SmartProxy.authorized.find(params['smart_proxy_id'])
    end

    def ports_from_params(params)
      # ranges = params[:ports].split(',')
      # ports = ranges.map do |range|
      #   range.split('-').map do |from, to|
      #     to.nil? ? from : (from..to).entries
      #   end
      # end
      # ports.flatten.map(&:chomp).map(&:to_i)
      params[:raw_ports]
    end

    def targeting_from_params(params)
      case params[:target_kind].downcase
      when 'direct'
        ::ForemanProbing::Targeting::Direct.new(:raw_targets => params[:direct])
      when 'subnet'
        ::ForemanProbing::Targeting::Subnet.new(:raw_targets => params[:subnet_id])
      when 'host'
        ::ForemanProbing::Targeting::Search.new(:raw_targets => params[:search_query])
      when 'proxy'
        ::ForemanProbing::Targeting::SubnetDiscovery.new
      end
    end
  end
end

app/models/foreman_probing/scan_host.rb
module ForemanProbing
  class ScanHost < ActiveRecord::Base

    belongs_to :scan
    belongs_to :host
    
  end
end

app/models/foreman_probing/service.rb
module ForemanProbing
  class Service < ActiveRecord::Base
    belongs_to :port

    def self.new_from_facts(name, facts)
      service = self.new
      service.name = name
      service.confidence = facts.fetch('confidence', 0)
      service.method = facts.fetch('method', 'table')
      # TODO: Process the rest of the attributes
      service
    end
  end
end

app/models/foreman_probing/targeting.rb
module ForemanProbing
  class Targeting < ActiveRecord::Base
    belongs_to :scan

    # Returns array of strings, suitable for direct passing into nmap
    def targets
      raise NotImplementedError
    end

    require_dependency(File.join(__FILE__.gsub(/\.rb$/, ''), '..', 'targeting', 'subnet.rb'))
  end
end

app/models/foreman_probing/targeting/direct.rb
module ForemanProbing
  class Targeting::Direct < Targeting

    # Either ip address or subnet in CIDR notation
    # def initialize(address_string)
    #   @addresses = parse_address_string!(address_string)
    # end

    def targets
      parse_address_string!(raw_targets).map do |addr|
        str = ''
        case addr[:family].to_s
        when 'inet'
          str += addr[:addr]
          str += '/' + addr[:netmask] unless addr[:netmask].nil?
        when 'inet6'
          # TODO: ipv6
          raise NotImplementedError
        else
          raise ArgumentError, "Unknown address family #{addr[:family]}"
        end
        str
      end
    end

    def target_kind
      'direct'
    end

    private

    # TODO: Do some validation
    def parse_address_string!(str)
      if str.is_a?(Array)
        str.map { |item| parse_address_string! item }.flatten
      elsif str.is_a? Hash
        str
      else
        # TODO: Somehow use IPAddr
        str.split(',').map do |ip|
          if ip =~ /(\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3})(\/(\d{1,2}))?/
            { :family => :inet, :addr => $1, :netmask => $3 }
          else
            # TODO: Match ipv6 here
          end
        end
      end
    end
  end
end

app/models/foreman_probing/targeting/search.rb
module ForemanProbing
  class Targeting::Search < ::ForemanProbing::Targeting
    # def initialize(search_query, hosts = nil)
    #   @search_query = search_query
    #   @hosts = hosts
    # end

    def targets
      @hosts ||= resolve_hosts!
      @targets ||= @hosts.map { |host| host.interfaces.map(&:ip) }.flatten
    end

    def target_kind
      'host'
    end

    def resolve_hosts!
      # @hosts = Host.authorized(RESOLVE_PERMISSION, Host)
      #              .search_for(@search_query)
      ::Host.authorized.search_for(raw_targets)
    end
  end
end

app/models/foreman_probing/targeting/subnet.rb
module ForemanProbing
  class Targeting::Subnet < ForemanProbing::Targeting
    def target_kind
      'subnet'
    end

    def subnet
      @subnet ||= ::Subnet.authorized.find(raw_targets.to_i)
    end

    def targets
      # TODO: This is ugly
      cidr = IPAddr.new(subnet.mask).to_i.to_s(2).count('1')
      @targets ||= "#{subnet.network}/#{cidr}"
    end
  end
end

app/models/foreman_probing/targeting/subnet_discovery.rb
module ForemanProbing
  class Targeting::SubnetDiscovery < Targeting

    def target_kind
      'proxy'
    end

    def targets
      []
    end
  end
end

app/controllers/foreman_probing/api/v2/scans_controller.rb
module ForemanProbing
  module Api::V2
    class ScansController < ::Api::V2::BaseController
      include ::Api::Version2
      include ::Foreman::Renderer

      resource_description do
        resource_id 'foreman_probing'
        api_version 'v2'
        api_base_url '/foreman_probing/api'
      end

      before_action :find_resource, :only => %w{show rerun}

      def resource_class
        ForemanProbing::Scan
      end

      api :GET, '/scans', N_('List scans')
      param_group :search_and_pagination, ::Api::V2::BaseController
      def index
        @scans = resource_scope.order(:id => 'desc').paginate(:page => params[:page])
      end

      api :POST, '/scans', N_('Create a scan')
      param :targeting_type, String, :required => true,
        :desc => N_('Type of targeting, one of %{options}') % { :options => ForemanProbing::ScanComposer::TARGETING_TYPES.join(', ') }
      param :scan_type, String, :required => true, :desc => N_('Type of the scan, one of %{options}') % { :options => %w{TCP UDP ICMP}.join(', ') }
      param :ports, String, :desc => N_('The ports to probe')
      param :proxy_id, :identifier, :required => true, :desc => N_('The smart proxy to run the scan from')
      param :direct, String, :desc => N_('Comma separated list of IPv4 addresses, subnets or ranges')
      param :subnet_id, :identifier, :desc => N_('ID of subnet to scan')
      param :search_query, String, :desc => N_('Scan hosts matching the search query')
      def create
        @composer = ScanComposer.new_from_params(params[:foreman_probing_scan])
        @scan = @composer.compose!
        @scan.save!
        task = ForemanTasks.async_task(::Actions::ForemanProbing::PerformScan,
                                       @scan,
                                       @scan.ports)
        @scan.task = task
        @scan.save!
        set_auto_refresh
        redirect_to @scan
      end

      api :POST, '/scans/:id', N_('Rerun scan')
      param :id, :identifier, :required => true, :desc => N_('ID of scan to rerun')
      def rerun
        composer = ScanComposer.new_from_scan(ForemanProbing::Scan.find(params['id']))
        @scan = composer.compose!
        @scan.save!
        task = ForemanTasks.async_task(::Actions::ForemanProbing::PerformScan,
                                       @scan,
                                       @scan.ports)
        @scan.task = task
        @scan.save!
        render :action => 'show'
      end

      api :GET, '/scans/:id', N_('Show scan')
      param :id, :identifier, :required => true, :desc => N_('ID of scan to show')
      def show; end
    end
  end
end

app/controllers/foreman_probing/hosts_controller.rb
module ForemanProbing
  # Example: Plugin's HostsController inherits from Foreman's HostsController
  class HostsController < ::HostsController
    before_action :find_resource, :only => :open_ports

    def open_ports
      render :partial => 'open_ports'
    end

    private

    define_action_permission ['open_ports'], :view
  end
end

app/controllers/foreman_probing/scans_controller.rb
module ForemanProbing
  class ScansController < ::ApplicationController

    def index
      @scans = resource_base.order(:id => 'desc').paginate(:page => params[:page])
    end

    def new
      @scan = ForemanProbing::Scan.new
      @scan.target_kind = params.fetch(:target_kind, 'direct')
      @scan.search_query = params[:search_query]
      @scan.targeting = ::ForemanProbing::Targeting.new
    end

    def create
      @composer = ScanComposer.new_from_params(params[:foreman_probing_scan])
      @scan = @composer.compose!
      @scan.save!
      task = ForemanTasks.async_task(::Actions::ForemanProbing::PerformScan,
                                     @scan,
                                     @scan.ports)
      @scan.task = task
      @scan.save!
      set_auto_refresh
      redirect_to @scan
    end

    def rerun
      composer = ScanComposer.new_from_scan(ForemanProbing::Scan.find(params['id']))
      @scan = composer.compose!

      render :action => 'new'
    end

    def show
      @scan = ::ForemanProbing::Scan.find(params['id'])
      set_auto_refresh
    end

    private

    def set_auto_refresh
      @auto_refresh = @scan.task.try(:pending?)
    end

  end
end

app/helpers/concerns/foreman_probing/hosts_helper_extensions.rb
module ForemanProbing
  module HostsHelperExtensions
    def host_title_actions(*args)
      title_actions(button_group(link_to(_('Probe'), new_foreman_probing_scan_path(:search_query => "name = #{args.first.name}", :target_kind => 'host'), :id => :run_button, :class => 'btn btn-default')))

      super(*args)
    end
  end
end

app/helpers/concerns/foreman_probing/subnet_helper_extensions.rb
module ForemanProbing
  module SubnetHelperExtensions
    def multiple_actions
      super + [[_('Probe'), new_job_invocation_path, false]]
    end
  end
end

app/views/foreman_probing/scans/index.html.erb
<% title _('Scans') %>

<% title_actions([new_link(_('Run Scan'))]) %>

<table class="table table-bordered table-condensed">
    <thead>
        <tr>
            <th>ID</th>
            <th>Scan type</th>
            <th>Ports</th>
            <th>Smart Proxy</th>
            <th>Targeting</th>
            <th>Run at</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @scans.each do |scan| %>
            <tr>
                <td><a href="<%= url_for(scan) %>"><%= scan.id %></a></td>
                <td><%= scan.scan_type %></td>
                <td><%= scan.ports.join(', ') %></td>
                <td><%= scan.smart_proxy.name %></td>
                <td><%= targeting_label(scan.targeting) %></td>
                <td><%= scan.task && scan.task.started_at %></td>
                <td><a href="<%= rerun_foreman_probing_scan_path(:id => scan.id) %>" class="btn">Rerun</a></td>
            </tr>
        <% end %>
    </tbody>
</table>
<%= will_paginate_with_info @scans %>

app/views/foreman_probing/scans/new.html.erb
<script>
  var target_kind_change_handler = function(element) {
      var value = element.value.toLowerCase();
      $('div.kind').each(function(child) {
          if(this.classList.contains('kind-' + value)) {
              $(this).show();
          } else {
              $(this).hide();
          }
      });
  };
  var scan_type_change_handler = function(element) {
    var value = element.value;
    var target = $('input#foreman_probing_scan_raw_ports').closest('div.clearfix');
    if(element.value != 'ICMP') {
      target.show();
    } else {
      target.hide();
    }
  };
</script>

<%= title _('Scan') %>
<%= form_for @scan do |f| %>

  <%= selectable_f f, :target_kind, @scan.target_kinds.map { |kind| [kind, kind.downcase] }, {}, :label => _('Target kind'), :onchange => 'target_kind_change_handler(this)' %>

  <div class="kind kind-subnet <%= @scan.target_kind != 'subnet' ? 'hidden' : '' %>">
    <%= selectable_f f, :subnet_id, Subnet.authorized.map { |s| ["#{s.name} (#{s.network}/#{s.mask}", s.id] },
                     {}, :label => 'Subnet' %>
  </div>

  <div class="kind kind-host <%= @scan.target_kind != 'host' ? 'hidden' : '' %>">
    <%= textarea_f f, :search_query, :label => _('Search query') %>
  </div>

  <div class="kind kind-direct <%= @scan.target_kind != 'direct' ? 'hidden' : '' %>">
    <%= text_f f, :direct, :label => _('IP Address'), :help_inline => _('Comma separated list of IPv4 addresses, subnets or ranges') %>
  </div>

  <%= selectable_f f, 'smart_proxy_id', SmartProxy.authorized.map { |p| [p.name, p.id] }, {}, :label => 'Smart proxy', :help_inline => _('Smart Proxy to run the scan from')  %>

  <%= selectable_f f, :scan_type, @scan.available_scan_types, {}, :label => _('Scan type'), :onchange => 'scan_type_change_handler(this)' %>

  <div class="raw-ports <%= @scan.scan_type == 'ICMP' ? 'hidden' : '' %>">
      <%= text_f f, :raw_ports, :label => _('Ports'), :help_inline => 'Single, port, coma-separated list or range FROM-TO' %>
  </div>

  <%= submit_or_cancel f, false, :cancel_path => foreman_probing_scans_path %>

<% end %>

app/views/foreman_probing/scans/show.html.erb
<% title 'Scan' %>

<!-- TODO: Buttons -->
<% if @scan.task %>
    <% title_actions(button_group(scan_task_buttons(@scan))) %>
<% end %>

<div class="col-md-6">
    <h4>Details</h4>
    <b><%= _("Smart proxy") %></b>: <a href="<%= url_for(@scan.smart_proxy) %>"><%= @scan.smart_proxy.name %></a><br>
    <b><%= _("Scan type") %></b>: <%= @scan.scan_type %><br>
    <% if @scan.scan_type != 'ICMP' %>
        <b><%= _("Ports") %></b>: <%= @scan.ports.join(', ') %><br>
    <% end %>
</div>

<div class="col-md-6 infoblock">
    <h4>Scanned hosts</h4>
    <% if @scan.task && %w(stopped paused).include?(@scan.task.state) %>
        <table class="table table-bordered table-condensed">
            <tr><th>Host</th><th>State</th></tr>
            <% @scan.hosts.each do |host| %>
                <tr><td><a href="<%= url_for(host) %>"><%= host.name %></a></td>
                    <td><%= host.probing_facet && host.probing_facet.status %></td>
                </tr>
            <% end %>
        </table>
    <% else %>
        <div class="alert alert-info">
            The task is still running.
        </div>
    <% end %>
</div>

<% if @auto_refresh %>
<script id="scan_show_refresh">
 setTimeout(function () {
     location.reload();
 }, 10000);
</script>
<% end %>