config/routes.rb
Rails.application.routes.draw do
  # get 'new_action', to: 'foreman_probing/hosts#new_action'
  namespace :foreman_probing do
    resources :scans, :only => [:create, :new, :show, :index] do
      member do
        get :rerun
      end
    end

    constraints(:id => /[^\/]+/) do
      resources :hosts do
        member do
          get 'open_ports'
        end
      end
    end

    namespace :api do
      scope "(:apiv)", :module => :v2, :defaults => {:apiv => 'v2'}, :apiv => /v2/, :constraints => ApiConstraints.new(:version => 2, :default => true) do
        resources :scans, :only => [:create, :index, :show] do
          member do
            get :rerun
          end
        end
      end
    end
  end
end

app/views/templates/ssh/add_public_keys.erb
<%#
kind: job_template
name: Add Public Keys - SSH Default
job_category: Commands
description_format: "Add Public Key %{public key}"
provider_type: SSH
template_inputs:
- name: public key
description: Public key to add to the host
input_type: user
required: true
%>
PUBLIC_KEY="<%= input("public key") %>"
SSH_DIR="${HOME}/.ssh"
AUTHORIZED_KEYS="${SSH_DIR/authorized_keys"

umask 077
[ -d "$SSH_DIR" ] || mkdir -p "$SSH_DIR"

if ! grep -q "$PUBLIC_KEY" "$SSH_DIR"; then
  echo "$PUBLIC_KEY" >> "$AUTHORIZED_KEYS"
fi

app/views/templates/ssh/register_content_host.erb
<%#
kind: job_template
name: Register Content Host - SSH Default
job_category: Commands
description_format: "Register Content Host using activation key %{activation key}"
provider_type: SSH
template_inputs:
- name: activation key
description: Name of the Activation Key to use for registering the host
input_type: user
required: true
- name: organization name
description: Name of the Organization to register the host to
input_type: user
required: true
%>
# Install Katello's certificates
yum localinstall -y <%= foreman_server_url %>/pub/katello-ca-consumer-latest.noarch.rpm

# Install subscription-manager
yum install -y subscription-manager

# Register the host
subscription-manager register \
  --org="<%= input("organization name") %> \
  --activationkey="<%= input("activation key") %>

# Enable repository with katello-agent
yum install -y http://fedorapeople.org/groups/katello/releases/yum/3.4/client/el7/x86_64/katello-client-repos-latest.rpm

# Install katello-agent
yum -y install katello-agent
systemctl enable goferd
systemctl start goferd

app/views/templates/ssh/register_puppet.erb
<%#
kind: job_template
name: Register Puppet - SSH Default
job_category: Commands
description_format: "Register Puppet"
provider_type: SSH
%>
yum install -y https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm
cat <<END > /etc/puppetlabs/puppet/puppet.conf
[agent]
server = <%= foreman_url %>
ca_server = <%= foreman_url %>
certname = <%= @host.certname %>
END

/opt/puppetlabs/puppet/bin/puppet agent --test

systemctl enable puppet
systemctl start puppet